# -*- coding: utf-8 -*-
"""출구조사_모든경우의수.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11A3Lm6ybb21NuiuM8xo21WwyGMOMGPjV
"""

import operator as op

from functools import reduce

def nCr(n, r):
    if n < 1 or r < 0 or n < r:
        raise ValueError
    r = min(r, n-r)
    numerator = reduce(op.mul, range(n, n-r, -1), 1)
    denominator = reduce(op.mul, range(1, r+1), 1)
    return numerator // denominator

print(nCr(34059720, 73297))